<?php
/**
 * Výchozí data (seed) + funkce pro jejich vložení.
 * -----------------------------------------------------------------------------
 * Data se vloží AUTOMATICKY při prvním připojení (viz scm_db_init_schema).
 * Vkládá se JEN do prázdných tabulek - živá data na serveru se nikdy nepřepíšou.
 */

declare(strict_types=1);

function scm_seed_data(PDO $db): array
{
    $inserted = ['events' => 0, 'programme' => 0, 'awards' => 0];

    // ---- TERMÍN akce ----
    if ((int)$db->query('SELECT COUNT(*) FROM termin')->fetchColumn() === 0) {
        $db->prepare('INSERT INTO termin (datum_cas) VALUES (?)')->execute(['2025-11-08T18:00']);
    }

    // ---- POZVÁNKA (obrázek) ----
    if ((int)$db->query('SELECT COUNT(*) FROM invitation')->fetchColumn() === 0) {
        $db->prepare('INSERT INTO invitation (image) VALUES (?)')->execute(['images/reservation/invation.png']);
    }

    // ---- STAV VSTUPENEK ----
    if ((int)$db->query('SELECT COUNT(*) FROM reservation_status')->fetchColumn() === 0) {
        $db->prepare('INSERT INTO reservation_status (is_active) VALUES (?)')->execute([0]);
    }

    // ---- PROGRAM galavečera ----
    if ((int)$db->query('SELECT COUNT(*) FROM programme')->fetchColumn() === 0) {
        $rows = [
            ['17:30 otevření sálu', '17:30 open hall'],
            ['18:00 slavnostní zahájení SAFE 25 U5 – U9', '18:00 SAFE 2024 opening ceremony'],
            ['Ocenění hráčů kategorií U5 – U9', 'Category U5 – U9 team awards'],
            ['Vyhlášení nejlepších hráčů U11 – muži/ženy', 'Best players awards U11 – muži/ženy'],
            ['Představení Miners klipu + křest', 'Miners clip premiere + launching ceremony'],
            ['Autogramiáda hostů', 'Guests autograph session'],
            ['Medailonky oceněných hráčů', 'Medallions of awarded players'],
            ['Afterparty', 'Afterparty'],
        ];
        $stmt = $db->prepare('INSERT INTO programme (description_cs, description_en, sort_order) VALUES (?,?,?)');
        foreach ($rows as $i => $r) { $stmt->execute([$r[0], $r[1], $i]); }
        $inserted['programme'] = count($rows);
    }

    // ---- MINULÉ ROČNÍKY ----
    if ((int)$db->query('SELECT COUNT(*) FROM events')->fetchColumn() === 0) {
        $rows = [
            ['<h2>2022</h2>', '<h2>2022</h2>', '<p>Prvn&iacute; a z&aacute;roveň jubilejn&iacute; des&aacute;t&yacute; ročn&iacute;k dř&iacute;ve tradičn&iacute; akce&nbsp;<strong>SAFE!</strong> Na programu byly rozhovory s hosty, oceněn&iacute; hr&aacute;čů a videa ze sez&oacute;ny.</p>', '<p>The first and at the same time the jubilee tenth year of the formerly traditional&nbsp;<strong>SAFE!</strong>&nbsp;The program included Guest interviews, player awards and videos from the season.</p>
<div class="first-gallery">&nbsp;</div>', '', '["images\/events/safe01.jpg","images\/events/safe02.jpg","images\/events/safe03.jpg","images\/events/safe04.jpg"]'],
            ['<h2>2023</h2>', '<h2>2023</h2>', '<p>Posledn&iacute; ročn&iacute;k akce&nbsp;<strong>SAFE</strong>&nbsp;byl neuvěřitelně nabit&yacute;! Na&scaron;e pozv&aacute;n&iacute; přijali n&aacute;sleduj&iacute;c&iacute; host&eacute;:</p>
<ul>
<li><strong>Franti&scaron;ek Bure&scaron;</strong>&nbsp;- statut&aacute;rn&iacute; n&aacute;městek prim&aacute;tora a člen Rady města Kladna</li>
<li><strong>Robert Bezděk</strong>&nbsp;- n&aacute;městek prim&aacute;tora a člen Rady města Kladna</li>
<li><strong>Petr Ditrich</strong>&nbsp;- předseda česk&eacute; baseballov&eacute; asociace</li>
<li><strong>Gabriel Waage</strong>&nbsp;- předseda česk&eacute; softballov&eacute; asociace</li>
<li><strong>Evženie Vot&iacute;nsk&aacute;</strong>&nbsp;- vedouc&iacute; PR a marketingu česk&eacute; baseballov&eacute; asociace</li>
<li><strong>Tom&aacute;&scaron; Duffek</strong>&nbsp;- baseballov&yacute; reprezentant Česk&eacute; republiky</li>
<li><strong>Martin Muž&iacute;k</strong>&nbsp;- baseballov&yacute; reprezentant Česk&eacute; republiky</li>
<li><strong>Filip Proch&aacute;zka</strong>&nbsp;- tren&eacute;r baseballov&eacute; reprezentace ČR U18</li>
<li><strong>Michala Kuchařov&aacute;</strong>&nbsp;- b&yacute;val&aacute; elitn&iacute; softballov&aacute; hr&aacute;čka</li>
<li><strong>Nela Jan&aacute;čkov&aacute;</strong>&nbsp;- softballov&aacute; reprezentantka Česk&eacute; republiky</li>
</ul>
<p>Tak vz&aacute;cn&iacute; host&eacute; nemohli zůstat jen tak sedět, a tak byla uspoř&aacute;d&aacute;na autogrami&aacute;da, kterou děti s &uacute;směvem přiv&iacute;taly. Nechybělo ani focen&iacute;.</p>', '<p>The last year of the event&nbsp;<strong>SAFE</strong>&nbsp;It was incredibly charged! Our invitation was accepted by the following guests:</p>
<ul>
<li><strong>Franti&scaron;ek Bure&scaron;</strong>&nbsp;- Statutory Deputy Mayor and Member of the Kladno City Council</li>
<li><strong>Robert Bezděk</strong>&nbsp;- Deputy Mayor and Member of the Kladno City Council</li>
<li><strong>Petr Ditrich</strong>&nbsp;- Chairman of the Czech Baseball Association</li>
<li><strong>Gabriel Waage</strong>&nbsp;- Chairman of the Czech Softball Association</li>
<li><strong>Evženie Vot&iacute;nsk&aacute;</strong>&nbsp;- Head of PR and Marketing of the Czech Baseball Association</li>
<li><strong>Tom&aacute;&scaron; Duffek</strong>&nbsp;- baseball representative of the Czech Republic</li>
<li><strong>Martin Muž&iacute;k</strong>&nbsp;- baseball representative of the Czech Republic</li>
<li><strong>Filip Proch&aacute;zka</strong>&nbsp;- Coach of the Czech U18 national baseball team</li>
<li><strong>Michala Kuchařov&aacute;</strong>&nbsp;- Former elite softball player</li>
<li><strong>Nela Jan&aacute;čkov&aacute;</strong>&nbsp;- softball representative of the Czech Republic</li>
</ul>
<p>Such distinguished guests could not just sit still, so an autograph session was organized, which the children with They greeted with a smile. There was also a photo shoot.</p>', '', '["images\/events/SAFE-225.jpg","images\/events/SAFE-380.jpg","images\/events/SAFE-396.jpg","images\/events/SAFE-125.jpg"]'],
            ['<h2>2024</h2>', '<h2>2024</h2>', '<p style="line-height: 1.5;">Jubilejn&iacute; des&aacute;t&yacute; ročn&iacute;k <strong>SAFE </strong>(3. v novodob&eacute; historii) byl oslavou nej&uacute;spě&scaron;něj&scaron;&iacute; sez&oacute;ny vůbec! V&iacute;tězstv&iacute; v několika lig&aacute;ch, udržen&iacute; Mužů v druh&eacute; nejvy&scaron;&scaron;&iacute; soutěži a hr&aacute;či Miners v reprezentac&iacute;ch. Proto jsme opět měli to &scaron;těst&iacute; a mohli představit vz&aacute;cn&eacute; hosty, kter&yacute;mi byli:</p>
<p><strong>Franti&scaron;ek Bure&scaron;</strong> - statut&aacute;rn&iacute; n&aacute;městek prim&aacute;tora a člen Rady města Kladna</p>
<p><strong>Robert Bezděk </strong>- n&aacute;městek prim&aacute;tora a člen Rady města Kladna</p>
<p><strong>Martin Vejvoda</strong> - &scaron;&eacute;ftren&eacute;r kladensk&yacute;ch Ryt&iacute;řů</p>
<p><strong>Michal M&uuml;ller</strong> - hlavn&iacute; tren&eacute;r extraligov&eacute;ho t&yacute;mu Eagles Praha, hlavn&iacute; tren&eacute;r baseballov&eacute; reprezentace U15</p>
<p><strong>Am&aacute;lie Chaloupkov&aacute;</strong> - softballov&aacute; reprezentantka ČR (U22 a Ženy)</p>
<p><strong>Karol&iacute;na Noskov&aacute; </strong>- softballov&yacute; reprezentantka ČR (U22)</p>
<p><strong>Zdeněk Ž&iacute;dek</strong> - rozhodč&iacute; druh&eacute; nejvy&scaron;&scaron;&iacute; baseballov&eacute; ligy v USA</p>
<p>Stejně jako v loňsk&eacute;m ročn&iacute;ku jsme uspoř&aacute;dali autogrami&aacute;du česk&yacute;ch reprezentantek.</p>', '<p style="line-height: 1.5;">The tenth anniversary edition of SAFE (the third in modern history) celebrated the most successful season ever! Victories in several leagues, the Men\'s team remaining in the second highest competition, and Miners players representing their countries. That\'s why we were lucky enough to welcome some distinguished guests, including:</p>
<p><strong>Franti&scaron;ek Bure&scaron;</strong> - Deputy Mayor and Member of the Kladno City Council</p>
<p><strong>Robert Bezděk</strong> - Deputy Mayor and Member of the Kladno City Council</p>
<p><strong>Martin Vejvoda </strong>- Head Coach of the Kladno Knights</p>
<p><strong>Michal M&uuml;ller </strong>- Head Coach of the Eagles Praha Extraliga team, Head Coach of the U15 national baseball team</p>
<p><strong>Am&aacute;lie Chaloupkov&aacute;</strong> - Czech national softball team player (U22 and Women)</p>
<p><strong>Karol&iacute;na Noskov&aacute;</strong> - Czech national softball team player (U22)</p>
<p><strong>Zdeněk Ž&iacute;dek </strong>- umpire in the second highest baseball league in the USA</p>
<p>As in last year\'s event, we organized an autograph session with the Czech national team players.</p>', '', '["images\/events/SAFE_0129.jpeg","images\/events/SAFE_0253.jpeg","images\/events/SAFE_0455.jpeg","images\/events/SAFE_0462.jpeg"]'],
            ['<h2>2025</h2>', '<h2>2025</h2>', '<p>Speciální ročník SAFE 25 byl oslavou nejen všech kategorií a nejlepších hráčů, ale především klubu jako takového. K příležitosti 35. výročí klubu jsme si nadělili dva veliké dárky - velký redesign webových stránek s přidáním nových stránek a funkcí a videoklip k Miners songu Budeme rubat, který složil Milan Koláčný. Třešničkou na dortu bylo uvedení čtyř zakladatelů kladenského oddílu do síně slávy.</p>
<p>Tak velkou oslavu jsme nemohli nechat náhodě, a tak jsme večerní show dali do rukou tomu nejpovolanějšímu - Jakubu Staříkovi. Spolu se Zuzanou Vosátkovou vytvořili parádní atmosféru.</p>
<p>Vážíme si i hostů, kteří přijali naše pozvání:</p>
<p><strong>Robert Bezděk</strong> - náměstek primátora a člen Rady města Kladna</p>
<p><strong>Magdaléna Kavanová</strong> - softballová reprezentantka ČR (Ženy)</p>
<p><strong>Veronika Pecková</strong> - softballová reprezentantka ČR (Ženy)</p>
<p><strong>Michaela Pecková</strong> - softballová reprezentantka ČR (Ženy)</p>
<p><strong>Lucie Halakucová</strong> - bývalá softballová reprezentantka ČR a kladenská odchovankyně</p>
<p>Po programu proběhla tradiční autogramiáda reprezentatek spolu s focením a natáčení rozhovorů s oceněnými hráči.</p>', '<p>The special SAFE 25 edition celebrated not only all categories and the best players, but above all the club itself. To mark the club\'s 35th anniversary, we gave ourselves two big gifts - a major redesign of the website with the addition of new pages and features, and a video clip for the Miners song Budeme rubat (We Will Mine), composed by Milan Koláčný. The icing on the cake was the induction of the four founders of the Kladno club into the Hall of Fame.</p>
<p>We couldn\'t leave such a big celebration to chance, so we put the evening show in the hands of the most qualified person - Jakub Stařík. Together with Zuzana Vosátková, they created a great atmosphere.</p>
<p>We also appreciate the guests who accepted our invitation:</p>
<p><strong>Robert Bezděk</strong> - representative of the City of Kladno</p>
<p><strong>Magdaléna Kavanová</strong> - Czech Republic softball representative (Women)</p>
<p><strong>Veronika Pecková</strong> - Czech national softball team player (women)</p>
<p><strong>Michaela Pecková</strong> - Czech national softball team player (women)</p>
<p><strong>Lucie Halakucová</strong> - former Czech national softball team player and Kladno native</p>
<p>After the program, there was a traditional autograph session with the national team players, along with photo shoots and interviews with the award-winning players.</p>', '', '["images\/events/251108_Miners_Gala-9716.jpg","images\/events/251108_Miners_Gala-0139.jpg","images\/events/251108_Miners_Gala-9292.jpg","images\/events/251108_Miners_Gala-0279.jpg"]'],
        ];
        $stmt = $db->prepare('INSERT INTO events (title_cs, title_en, description_cs, description_en, image_path, images, sort_order) VALUES (?,?,?,?,?,?,?)');
        foreach ($rows as $i => $r) { $stmt->execute([$r[0], $r[1], $r[2], $r[3], $r[4], $r[5], $i]); }
        $inserted['events'] = count($rows);
    }

    // ---- OCENĚNÍ HRÁČI ----
    if ((int)$db->query('SELECT COUNT(*) FROM awards')->fetchColumn() === 0) {
        $rows = [
            [2025, 'EXTRA', 'Little League, nár. kv., 3. MÍSTO &ndash; Kateřina Hergetová', 'Little League, CR qualifier, 3<sup>RD</sup> PLACE &ndash; Kateřina Hergetová', 'S výběrem Bohemia se utkala v národní kvalifikaci proti ostatním českým týmům a skončila na 3. místě.', 'Bohemia competed against other Czech teams in the national qualifiers and finished in third place.', 'images/awards/spec-Kacka.png'],
            [2025, 'EXTRA', 'Little League, nár. kv., 3. MÍSTO &ndash; Julie Rákosníková', 'Little League, CR qualifier, 3<sup>RD</sup> PLACE &ndash; Julie Rákosníková', 'S výběrem Bohemia se utkala v národní kvalifikaci proti ostatním českým týmům a skončila na 3. místě.', 'Bohemia competed against other Czech teams in the national qualifiers and finished in third place.', 'images/awards/spec-Juli.png'],
            [2025, 'EXTRA', 'Little League, nár. kv., 3. MÍSTO &ndash; Alice Škardová', 'Little League, CR qualifier, 3<sup>RD</sup> PLACE &ndash; Alice Škardová', 'S výběrem Bohemia se utkala v národní kvalifikaci proti ostatním českým týmům a skončila na 3. místě.', 'Bohemia competed against other Czech teams in the national qualifiers and finished in third place.', 'images/awards/spec-Alice.png'],
            [2025, 'EXTRA', 'Little League, nár. kv., 3. MÍSTO &ndash; Jan Herget', 'Little League, CR qualifier, 3<sup>RD</sup> PLACE &ndash; Jan Herget', 'Byl headcoachem výběru Bohemia, který se utkal v národní kvalifikaci proti ostatním českým týmům a skončil na 3. místě.', 'He was a heacoach of team Bohemia, who competed against other Czech teams in the national qualifiers and finished in third place.', 'images/awards/spec-Hergy.png'],
            [2025, 'EXTRA', 'Little League, nár. kv., 3. MÍSTO &ndash; Dagmar Rákosníková', 'Little League, CR qualifier, 3<sup>RD</sup> PLACE &ndash; Dagmar Rákosníková', 'Byla asistentkou výběru Bohemia, který se utkal v národní kvalifikaci proti ostatním českým týmům a skončil na 3. místě.', 'She was an assistant of headcoach of team Bohemia, who competed against other Czech teams in the national qualifiers and finished in third place..', 'images/awards/spec-Dasa.png'],
            [2025, 'EXTRA', 'ME U15, 2. MÍSTO &ndash; Jan Svoboda', 'ECH U15, 2<sup>ND</sup> PLACE &ndash; Jan Svoboda', 'Honza byl letos součástí týmu, který předvedl skvělý výkon v semifinále Mistrovství Evropy, čímž si vysloužil i postup na Mistrovství světa.', 'This year, Honza was part of the team that put in a great performance in the semifinals of the European Championships, earning them a spot in the World Championships.', 'images/awards/spec-Honzik.png'],
            [2025, 'EXTRA', 'ME U15, 2. MÍSTO &ndash; Petr Baroch', 'ECH U15, 2<sup>ND</sup> PLACE &ndash; Petr Baroch', 'Petr byl asistentem týmu, který předvedl skvělý výkon v semifinále Mistrovství Evropy, čímž si vysloužil i postup na Mistrovství světa.', 'Peter was an assistant of the team that put in a great performance in the semifinals of the European Championships, earning them a spot in the World Championships.', 'images/awards/spec-Petr.png'],
            [2025, 'EXTRA', 'K-Baseball Series &ndash; Ondřej Vostatek', 'K-Baseball Series &ndash; Ondřej Vostatek', 'Ondra dosáhl dalšího důležitého milníku jak ve své kariéře, tak pro klub Miners, když se jako první Minersák v historii probojoval na akci baseballového národního týmu mužů ČR.', 'Ondra achieved another important milestone in his career and for the Miners club when he became the first Miners player in history to make it to the Czech Republic\'s national men\'s baseball team.', 'images/awards/spec-Ondra.png'],
            [2025, 'EXTRA', 'ME ŽEN, 5. MÍSTO &ndash; Michaela Čurillová', 'WECH, 5<sup>TH</sup> PLACE &ndash; Michaela Čurillová', 'Míše se poprvé podařilo probojovat do softballového národního týmu žen ČR, se kterým v rámci přípravy procestovala Holandsko, Kanadu a Japonsko. Na domácím ME obsadil tým 5.místo.', 'Míša made it onto the Czech women\'s national softball team for the first time, traveling to the Netherlands, Canada, and Japan as part of her training. The team took 5th place at the European Championships held in the Czech Republic.', 'images/awards/spec-Misa.png'],
            [2025, 'UMP', 'Rozhodčí roku &ndash; Vojtěch Šuranyi', 'Umpire of the year &ndash; Vojtěch Šuranyi', 'O vítězi rozhodla jeho schopnost vést i velmi vypjatá utkání s ledovým klidem a dobrá schopnost komunikace s trenéry, díky které obtížné situace s přehledem zvládal', 'The winner was determined by his ability to lead even very tense matches with ice-cold calm and his good communication skills with coaches, thanks to which he was able to handle difficult situations with ease.', 'images/awards/Rozhodci_2.png'],
            [2025, 'MUŽI', 'MVP &ndash; Vojtěch Kuklík', 'MVP &ndash; Vojtěch Kuklík', 'Vojta byl v roce 2025 velkou oporou týmu. Nastupoval na klíčových pozicích catchera, první mety i zadopolaře a stal se důležitým článkem mužstva v 1. lize. Hostoval také v extraligové Kotlářce Praha, kde pomohl týmu udržet nejvyšší soutěž i pro další sezónu. V dresu Miners Kladno se stal historicky prvním hráčem, kterému se podařilo dosáhnout cyclu (tedy odpálit všechny druhy odpalů v jednom zápase - single, double, triple, homerun). Po sezóně odletěl na dva měsíce do USA do akademie PRO 5, kde usiluje o možnost nastoupit na univerzitu a posunout tak svou kariéru ještě dál. Držíme mu palce, aby nadále skvěle reprezentoval náš klub i český baseball.', 'Vojta was a great support to the team in 2025. He played key positions as catcher, first baseman, and outfield, becoming an important member of the team in the 1st League. He also played for Kotlářka Praha in the Extraliga, where he helped the team remain in the top league for another season. Wearing the Miners Kladno jersey, he became the first player in history to achieve a cycle (i.e., hitting all types of hits in one game - single, double, triple, homerun). After the season, he flew to the USA for two months to attend the PRO 5 academy, where he is striving for the opportunity to attend university and take his career even further. We wish him the best of luck in continuing to represent our club and Czech baseball so well.', 'images/awards/Muzi MVP.png'],
            [2025, 'ŽENY', 'MVP &ndash; Lucie Šubrtová', 'MVP &ndash; Lucie Šubrtová', 'Lucie je velmi cennou univerzální hráčkou. V poli dokáže zaskočit v podstatě na jakékoliv pozici, kde působí jistě a spolehlivě. Výrazně tým podržela také na nadhozu. V útoku je její nejsilnější zbraní útočná ulejvka a velmi rychlý běh. Dokáže nejen získat metu, ale i efektivně posunout běžce vpřed a vyvíjet tak tlak na obranu. Posty - nadhoz, spojka, 2. meta i vnější pole', 'Lucie is a very valuable utility player. She can play any position in the field, where she performs confidently and reliably. She also significantly supported the team in pitching. Her strongest weapons in offense are her aggressive bunts and very fast running. She can not only get on base, but also effectively move runners forward and put pressure on the defense. Positions - pitcher, shortstop, second base, and outfield', 'images/awards/Zeny MVP.png'],
            [2025, 'U16s', 'Cena trenéra &ndash; Hana Petrášová', 'Coach\'s Award &ndash; Hana Petrášová', 'Na Hance je vidět nadšení a odhodlání. Pro nikoho není snadné naskočit do rozjetého rychlíku, ale Hanka se s tím pere nadmíru dobře. Jen tak dál!', 'Hanka\'s enthusiasm and determination are clear to see. It\'s not easy for anyone to jump on a moving train, but Hanka is doing extremely well. Keep it up!', 'images/awards/U16s CT.png'],
            [2025, 'U15', 'Nejlepší pálkař &ndash; Jan Svoboda', 'Best Hitter &ndash; Jan Svoboda', 'Honza, stejně jako v loňské sezóně, podával stabilní výkony na pálce. Dokázal trefovat míče s jistotou a většina jeho odpalů byla vícemetová. Nechyběly ani homeruny.', 'Honza, just like last season, delivered consistent performances at bat. He was able to hit the ball with confidence, and most of his hits were multi-base hits. There were even some home runs.', 'images/awards/U15 palkar.png'],
            [2025, 'U15', 'Nejlepší polař &ndash; Matěj Štilip', 'Best Fielder &ndash; Matěj Štilip', 'Matěj byl spolehlivým pilířem obrany týmu. Jako catcher výborně kontroloval pokusy o krádeže met a v případě potřeby dokázal zaskočit jak ve vnitřním, tak i ve vnějším poli.', 'Matěj was a reliable pillar of the team\'s defense. As a catcher, he excelled at controlling stolen base attempts and, when necessary, was able to fill in both in the infield and outfield.', 'images/awards/U15 polar.png'],
            [2025, 'U15', 'Cena trenéra &ndash; Martin Herget', 'Coach\'s Award &ndash; Martin Herget', 'Martin si odnáší cenu díky své univerzálnosti. Jeho schopnost zaskočit prakticky na jakékoli pozici v poli je pro tým neocenitelná. I když nemá stálý post, dokáže se bez problémů přizpůsobit a odehrát kvalitní výkon téměř kdekoli.', 'Martin wins the award thanks to his universality. His ability to fill virtually any position on the field is invaluable to the team. Even though he doesn\'t have a permanent position, he can easily adapt and perform well almost anywhere.', 'images/awards/U15 CT.png'],
            [2025, 'U13', 'Nejlepší pálkař &ndash; Filip Posselt', 'Best Hitter &ndash; Filip Posselt', '„Fíla“ na pálce předváděl stabilní výkon po celou sezónu a může se tak chlubit nejvyšším pálkařským průměrem 0.385. Fílu zdobí trpělivost a dobré čtení nadhozů. Z toho také pramení vysoký počet obdržených met zdarma. Tvrdé a daleké odpaly u něj nebyli výjimkou. Zaslouženě BEST HITTER.', '"Fíla" showed consistent performance at bat throughout the season and can boast the highest batting average of .385. Fíla is known for his patience and good pitch reading. This also results in a high number of free bases. Hard and long hits were no exception for him. Deservedly named BEST HITTER.', 'images/awards/U13 palkar.png'],
            [2025, 'U13', 'Nejlepší polař &ndash; Václav Svoboda', 'Best Fielder &ndash; Václav Svoboda', 'Univerzál, makáč a srdcař s výborným přehledem a citem pro hru. S neuvěřitelným rozsahem byl oporou především na spojce. Jako nadhazovač má dobrou kontrolu a nejednoho pálkaře potrápil svým „padajícím listem“. Když bylo třeba, perfektně zachytal na kečrovi.', 'An utility player, hard worker, and passionate player with excellent vision and feel for the game. With his incredible range, he was a mainstay at shortstop. As a pitcher, he has good control and has troubled many a batter with his "falling leaf" pitch. When needed, he was a perfect catcher.', 'images/awards/U13 polar.png'],
            [2025, 'U13', 'Cena trenéra &ndash; Jan Rákosník', 'Coach\'s Award &ndash; Jan Rákosník', 'Honza „Rákoska, Rakovník, Baky“ Rákosník - jedna z hlavních opor v poli, na pálce i nadhozu. Velký srdcař, dříč a týmový hráč. V dugoutu neúnavný povzbuzovač a rozjížděč chorálů. Letos si vysloužil novou (další) přezdívku „pan BB“ (32 obdržených met zadarmo).', 'Honza "Rákoska, Rakovník, Baky" Rákosník - one of the main pillars in the field, at bat, and on the mound. A big heart, hard worker, and team player. In the dugout, he is a tireless cheerleader and chant leader. This year, he earned a new (another) nickname, "Mr. BB" (32 free bases).', 'images/awards/U13 CT.png'],
            [2025, 'U13s', 'Nejlepší pálkař &ndash; Kateřina Hergetová', 'Best Hitter &ndash; Kateřina Hergetová', '79 startů na pálce, 30 hitů, z toho 5 doublů a 4 triply. K tomu 10 RBI a 10 ukradených met – tahle hráčka dokáže nejen trefit míček, ale i složit ulejvku na poslední chvíli a obětovat se pro tým. Pilná, svědomitá a svým přístupem příkladem pro ostatní.', '79 at-bats, 30 hits, including 5 doubles and 4 triples. Add to that 10 RBIs and 10 stolen bases – this player can not only hit the ball, but also make a drag bunt and sacrifice herself for the team. Diligent, conscientious, and an example to others with her attitude.', 'images/awards/U13s palkar.png'],
            [2025, 'U13s', 'Nejlepší polař &ndash; Alice Škardová', 'Best Fielder &ndash; Alice Škardová', 'Týmová opora, která stojí za nejedním vítězstvím. Na catcherovi drží obranu pevně v rukou, znepříjemňuje běžcům každý pokus o krádež mety a zároveň dokáže podržet i na pálce. Když nehraje na catcherovi, tak drží tým na shortstopu nebo na nadhozu.', 'A team pillar who has been behind many victories. As catcher, she keeps the defense firmly in her hands, makes every attempt to steal a base difficult for runners, and can also hold her own at bat. When she\'s not playing catcher, she keeps the team going at shortstop or on the mound.', 'images/awards/U13s polar.png'],
            [2025, 'U13s', 'Cena trenéra &ndash; Maya Caroline Tatransky', 'Coach\'s Award &ndash; Maya Caroline Tatransky', 'Snaha je její třetí jméno! Ani dojíždění ji nezastaví — na trénincích chybí jen výjimečně a její nasazení je inspirací pro ostatní. Ke konci sezóny navíc ukázala, že píle se vyplácí – přibylo trefených míčů i úspěšných odpalů!', 'Effort is her middle name! Even commuting doesn\'t stop her — she rarely misses training sessions, and her dedication is an inspiration to others. At the end of the season, she proved that hard work pays off — she got more contacts and had more successful hits', 'images/awards/U13s CT.png'],
            [2025, 'U11', 'Nejlepší pálkař &ndash; Jindřich Valoušek', 'Best Hitter &ndash; Jindřich Valoušek', 'Jindrův pálkařský průměr 0,333 ho jasně vystřelil na pozici pálkařské jedničky. Navíc v průběhu sezony zaznamenal velký posun a jistotu při čtení míčů a získal také sílu a obratnost v pálkařské technice. Díky tomu posouvá hráče po metách a i sám se často dostává do hry.', 'Jindra\'s batting average of .333 clearly propelled him to the position of lead-off hitter. In addition, he made significant progress during the season in reading pitches and gained strength and agility in his batting technique. Thanks to this, he moves players around the bases and often gets into the game himself.', 'images/awards/U11 palkar.png'],
            [2025, 'U11', 'Nejlepší polař &ndash; Vojta Doubek', 'Best Fielder &ndash; Vojta Doubek', 'Vojta se může pyšnit výbornou hrou ve středním poli, kde vychytá téměř cokoli. Pochlubit se může také svými lety vzduchem a rybičkami, po kterých míč skončí bezpečně v rukavici. Díky tomu drží za druhou metou soupeře často v šachu.', 'Vojta boasts excellent play in the center field, where he catches almost anything. He can also boast his leaps through the air and diving catches, after which the ball ends up safely in his glove. Thanks to this, he often keeps the opponent\'s second base in check.', 'images/awards/U11 polar.png'],
            [2025, 'U11', 'Cena trenéra &ndash; Tomáš Kulhánek', 'Coach\'s Award &ndash; Tomáš Kulhánek', 'Tomáš cenu získává za konzistentní a aktivní výkon zejména na pozici catchera, kdy s jistotou řídí hru a je oporou pro nadhazovače. Současně nelze přehlédnout také jeho skvělý výkon na pálce. Je důležitou oporou týmu.', 'Tomáš receives the award for his consistent and active performance, especially as a catcher, where he confidently directs the game and supports the pitchers. At the same time, his excellent performance at bat cannot be overlooked. He is an important pillar of the team.', 'images/awards/U11 CT.png'],
            [2025, 'U11s', 'Nejlepší pálkař &ndash; Nicol Barešová', 'Best Hitter &ndash; Nicol Barešová', 'Titul nejlepší pálkařky sezóny si letos odnáší Nicol Barešová, která na pálce předváděla naprostou jistotu a sílu. S výborným pálkařským průměrem 0.625. Její razantní odpaly často létaly hluboko do zadního pole, nejednou narazily až do plotu. Nicol byla po celou sezónu symbolem stálé formy, klidu a sebevědomí na pálce, díky čemuž výrazně pomohla týmu k úspěchům.', 'The title of best batter of the season goes to Nicol Barešová, who showed complete confidence and power at bat. With an excellent batting average of .625, her powerful hits often flew deep into the outfield, sometimes even hitting the fence. Throughout the season, Nicol was a symbol of consistency, calmness, and confidence at bat, which greatly contributed to the team\'s success.', 'images/awards/U11s palkar.png'],
            [2025, 'U11s', 'Nejlepší polař &ndash; Inna Barochová', 'Best Fielder &ndash; Inna Barochová', 'Cenu pro nejlepší polařku sezóny získává Inna Barochová, která si svými výkony pevně vybojovala stálé místo na druhé metě. Během celé sezóny předváděla rychlé ruce a přesné přihrávky, díky nimž dokázala několikrát zahrát efektní double outy. Její spolehlivost v obraně potvrzuje i nejvyšší fielding průměr 0.935, kterým jen těsně předčila své spoluhráčky.', 'The award for the best female player of the season goes to Inna Barochová, who has firmly secured her place at second base with her performances. Throughout the season, she demonstrated quick hands and accurate throws, which enabled her to make several spectacular double outs. Her reliability in defense is confirmed by her fielding average of 0.935, which was just ahead of her teammates.', 'images/awards/U11s polar.png'],
            [2025, 'U11s', 'Cena trenéra &ndash; Agáta Hnízdilová', 'Coach\'s Award &ndash; Agáta Hnízdilová', 'Cenu trenéra letos získává Agáta Hnízdilová, která během sezóny udělala obrovský pokrok jak na pálce, tak i v poli. Na pálce dokázala tvrdě trefovat míče až na trávu, čímž nejednou potěšila trenéry i celý tým. Výrazně se však ukázala také na nadhozu, kde na Mistrovství ČR dostala velkou šanci a ihned ji využila – předvedla čtyři klíčové zákroky, které pomohly týmu k důležitým outům.', 'This year\'s Coach of the Year award goes to Agáta Hnízdilová, who made tremendous progress both at bat and in the field during the season. At bat, she was able to hit the ball hard onto the grass, which delighted the coaches and the entire team on more than one occasion. However, she also made a significant impact on the mound, where she was given a big opportunity at the Czech Republic Championships and immediately took advantage of it – she made four key plays that helped the team get important outs.', 'images/awards/U11s CT.png'],
            [2024, 'EXTRA', 'Little League, 2. MÍSTO &ndash; Adéla Badinková', 'Little League, 2<sup>ND</sup> PLACE &ndash; Adéla Badinková', 'Holky prošly s výběrem Bohemia vypjatou kvalifikací v Praze, kde si po otočce v poslední směně vysloužily místo na Evropsko-africké kvalifikaci v polském Kutnu. Tam jen těsně padly s italským výběrem, a tak se jim americké brány uzavřely.', 'The girls went through a tense qualification with the Bohemia team in Prague, where, after a last-inning turnaround, they earned a spot at the European-African qualifiers in Kutno, Poland. There, they only narrowly lost to the Italian team, so the American gates were closed to them.', 'images/awards/spesl_ada.png'],
            [2024, 'EXTRA', 'Little League, 2. MÍSTO &ndash; Alice Škardová', 'Little League, 2<sup>ND</sup> PLACE &ndash; Alice Škardová', 'Holky prošly s výběrem Bohemia vypjatou kvalifikací v Praze, kde si po otočce v poslední směně vysloužily místo na Evropsko-africké kvalifikaci v polském Kutnu. Tam jen těsně padly s italským výběrem, a tak se jim americké brány uzavřely.', 'The girls went through a tense qualification with the Bohemia team in Prague, where, after a last-inning turnaround, they earned a spot at the European-African qualifiers in Kutno, Poland. There, they only narrowly lost to the Italian team, so the American gates were closed to them.', 'images/awards/spesl_ala.png'],
            [2024, 'EXTRA', 'ODM, 5. MÍSTO &ndash; Amélie Draxlerová', 'ChYO, 5<sup>TH</sup> PLACE &ndash; Amélie Draxlerová', 'Áma se dostala do výběru Středočeského kraje, který bojoval po 19 letech na Olympiádě dětí a mládeže. Smolný začátek zkomplikoval středočeškám turnaj, a tak dosáhly na 5. místo.', 'Áma made it to the Central Bohemian Region selection, which competed in the Children and Youth Olympics for the first time in 19 years. An unlucky start complicated the tournament for the Central Bohemian team, and they reached 5th place.', 'images/awards/spesl_ama.png'],
            [2024, 'EXTRA', 'PONY WS, 2. MÍSTO &ndash; Vojtěch Kuklík', 'PONY WS, 2<sup>ND</sup> PLACE &ndash; Vojtěch Kuklík', 'Vojtěch společně s pražskou akademií vybojoval postup na Pony League World Series, kde kluci narazili na přemožitele až ve finále, a tak odjeli ze Spojených států se stříbrnou medailí.', 'Vojtěch, together with the Prague academy, advanced to the Pony League World Series, where the boys met their conquerors in the finals, and so they left the United States with a silver medal.', 'images/awards/spesl_vojta.png'],
            [2024, 'EXTRA', 'DIBAT, 3. MÍSTO & ME U18, 7. MÍSTO & PONY WS, 2. MÍSTO &ndash; Ondřej Vostatek', 'DIBAT, 3<sup>RD</sup> PLACE & ECH U18, 7<sup>TH</sup> PLACE & PONY WS, 2<sup>ND</sup> PLACE &ndash; Ondřej Vostatek', 'Ondra zažil skvělou sezónu, která začala 3. místem na prestižním turnaji akademií, pokračovala 7. místem na Mistrovství Evropy do 18 let a léto zakončil 2. místem na Pony League World Series. Navíc byl jmenován MVP v Mužích.', 'Ondra had a great season, starting with a 3rd place finish at the prestigious academy tournament, continuing with a 7th place finish at the European U18 Championships, and ending the summer with a 2nd place finish at the Pony League World Series. He was also named Men\'s MVP.', 'images/awards/spesl_ondra.png'],
            [2024, 'EXTRA', 'ODM, 5. MÍSTO & ME U22, 4. MÍSTO &ndash; Michaela Čurillová', 'ChYO, 5<sup>TH</sup> PLACE & ECH U22, 4<sup>TH</sup> PLACE &ndash; Michaela Čurillová', 'Míša se v minulé sezóně připravovala na Mistrovství Evropy do 22 let, kde nakonec holky skončily čtvrté a přitom stihla ještě Olympiádu dětí a mládeže z pozice trenérky, kde se s týmem umístila na 5. místě.', 'Last season, Míša prepared for the European U22 Championship, where the girls ultimately finished fourth, and she also managed to attend the Children and Youth Olympics as a coach, where she and the team placed 5th.', 'images/awards/spesl_misa.png'],
            [2024, 'UMP', 'Rozhodčí roku &ndash; Aleš Rak', 'Umpire of the year &ndash; Aleš Rak', 'Dostává tuto cenu za vynikající reprezentaci klubu jako rozhodčí na zápasech extraligy. Rozhodoval mezinárodní zápasy Pražského baseballového týdne i další zápasy reprezentace ČR. Velké díky mu patří také za organizaci rozhodčích pro zápasy Miners v celé sezóně.', 'He receives this award for his outstanding representation of the club as an umpire in extra league games. He has umpired international games of the Prague Baseball Week as well as other matches of the Czech national team. A big thank you also goes to him for organizing the umpires for Miners games throughout the season.', 'images/awards/rozhodci.png'],
            [2024, 'MUŽI', 'MVP &ndash; Ondřej Vostatek', 'MVP &ndash; Ondřej Vostatek', 'Byl letos pilířem týmu a ukázal svůj výjimečný talent a odhodlání. Již v únoru se dostal do výběru reprezentace a odcestoval na přípravný kemp do Portorika, kde na nadhazovacím kopci podal skvělý výkon. Další významný úspěch přišel na turnaji Pony League, kde házel ve finále a pomohl týmu k vítězství, které jim otevřelo cestu na prestižní turnaj v USA. Během sezóny hájil nejen barvy našeho klubu v První lize, ale svými výkony se dostal i do extraligového týmu Tempa Praha. Díky svému nasazení a výkonům se nakonec probojoval až do reprezentace kategorie U18. Je příkladem neúnavné píle a talentu, který inspiruje ostatní hráče a posouvá úroveň našeho týmu stále výš.', 'He was a pillar of the team this year and showed his exceptional talent and determination. Already in February, he was selected for the national team and traveled to a training camp in Puerto Rico, where he performed brilliantly on the pitching mound. Another significant success came at the Pony League tournament, where he pitched in the final and helped the team win, which opened the way for them to the prestigious tournament in the USA. During the season, he not only defended the colors of our club in the First League, but also got into the extra league team Tempa Praha with his performances. Thanks to his commitment and performances, he eventually made it to the U18 national team. He is an example of tireless diligence and talent that inspires other players and pushes the level of our team ever higher.', 'images/awards/muzi_mvp.png'],
            [2024, 'ŽENY', 'MVP &ndash; Romana Roithová', 'MVP &ndash; Romana Roithová', 'Hostuje v týmu Miners již 5. sezónu z klubu Softball Lobkovice. Hraje na postu nadhazovačky a na první metě. Pálkaře trápí zejména změnou rychlostí nadhozu. Na pálce jsou její silnou zbraní útočné ulejvky a rychlý běh po metách.', 'She has been a guest on the Miners team for the 5th season from the Lobkovice Softball Club. She plays as a pitcher and first base. She mainly troubles batters with her change in pitch speed. At bat, her strong weapons are offensive throws and quick base running.', 'images/awards/zeny_mvp.png'],
            [2024, 'U16s', 'Nejlepší pálkař &ndash; Amálie Václavíková', 'Best Hitter &ndash; Amálie Václavíková', 'Díky rychlým nohám se často dokázala dostat na metu dříve než míč, a tak role první pálkařky ji sedla. Na finálovém turnaji měla důležité odpaly a seozónu zakončila s pálkařským průměrem .412.', 'With her quick feet, she was often able to get to base before the ball, making her a natural fit for the leadoff hitter. She had some important hits in the final tournament and finished the season with a .412 batting average.', 'images/awards/u16s_palkar.png'],
            [2024, 'U16s', 'Nejlepší polař &ndash; Alice Škardová', 'Best Fielder &ndash; Alice Škardová', 'Na hřišti ji prostě nepřehlédnete a ukázala to i v kategorii, kam bude věkově zapadat až za dva roky. Její konzistentní výkony byly velmi důležité pro cenná vítěztsví. Na finálovém turnaji jí byla přisouzena role spojky, zatímco celou sezónu odehrála na dvojce. Zvládla to velmi slušně a tak její sezónní polařská statistika se zastavila na čísle .905.', 'You simply cannot miss her on the field and she showed it even in a category where she will fit into her age group in two years. Her consistent performances were very important for valuable victories. In the final tournament, she was assigned the role of shortstop, while she played the entire season at number two. She managed it very well and her season field statistics stopped at number .905.', 'images/awards/u16s_polar.png'],
            [2024, 'U16s', 'Cena trenéra &ndash; Amélie Draxlerová', 'Coach\'s Award &ndash; Amélie Draxlerová', 'Byla stěžejní hráčkou pro získání titulu. Celou sezónu předváděla výborné výkony na nadhozu, ze zápasů si odnášela průměrně 7 strikeoutů a průměrně obdržela pouze půl bodu za směnu. Oporou byla také na jedničce, kde ji neprošel ani jeden míč. Titul nejužitečnější hráčky ji náleží i díky výborné pálce a pálkařskému průměru .487. Svojí pílí si vybojovala i účast v týmu na Olympiádě dětí a mládeže.', 'She was a key player in winning the title. She showed excellent pitching performances throughout the season, averaging 7 strikeouts and allowing only half a run per inning. She was also a mainstay at number one, where she didn\'t walk a single ball. She also earned the title of Most Valuable Player thanks to her excellent bat and batting average of .487. With her hard work, she also earned a spot on the team for the Children and Youth Olympics.', 'images/awards/u16s_cenaTrenera.png'],
            [2024, 'U15', 'Nejlepší pálkař &ndash; Jan Svoboda', 'Best Hitter &ndash; Jan Svoboda', 'Souboj o nejlepšího pálkaře byl velmi těsný až do konce sezóny. Nkonec ho zaslouženě vyhrál rozdílem jednoho jediného odpalu s pálkařským průměrem .463.', 'The battle for the best batting title was very close until the end of the season. In the end, he deservedly won it by one hit with a batting average of .463.', 'images/awards/u15_palkar.png'],
            [2024, 'U15', 'Nejlepší polař &ndash; Jakub Mareček', 'Best Fielder &ndash; Jakun Mareček', 'Cena nejlepšího polaře mu právem náleží za stabilní výkon na nadhazovacím kopci. Za celou sezónu odházel více než 500 nadhozů a ii podle dalších statistik se jednoznačně zařadil na první místo mezi nadhazovači v týmu.', 'The award for best fielder is rightfully his for his consistent performance on the mound. He threw more than 500 pitches throughout the season and according to other statistics, he clearly ranked first among the pitchers on the team.', 'images/awards/u15_polar.png'],
            [2024, 'U15', 'Cena trenéra &ndash; Matěj Štilip', 'Coach\'s Award &ndash; Matěj Štilip', 'Cenu trenérů dostává jako nejužitečnější hráč týmu. Byl největším tahounem týmu jak na pálce tak v obreně. Rovněž reprezentoval Miners v národním týmu U15.', 'He received the Coaches\' Award as the team\'s most valuable player. He was the team\'s biggest force both at bat and in the ring. He also represented the Miners on the U15 national team.', 'images/awards/u15_cenaTrenera.png'],
            [2024, 'U13', 'Nejlepší pálkař &ndash; Lukáš Lev', 'Best Hitter &ndash; Lukáš Lev', 'Letošním pálkařským statistikám jednoznačně kraloval. Pálkařský průměr .478 hovoří za vše. Taktéž největší počet stažených bodů a navíc dva homeruny potrvrzují nejlepšího pálkaře týmu U13 v letošním roce.', 'He clearly reigned supreme in this year\'s batting statistics. His batting average of .478 speaks for itself. Also, the highest number of runs scored and two home runs confirm him as the best batsman on the U13 team this year.', 'images/awards/u13_palkar.png'],
            [2024, 'U13', 'Nejlepší polař &ndash; Ondřej Labuť', 'Best Fielder &ndash; Ondřej Labuť', 'Kraluje polařským statistikám. Má největší počet odehraných zápasů, jistota na první metě a jrho univerzálnost mu vynesly titul nejlepšího polaře týmu U13.', 'He reigns supreme in fielding statistics. He has the most games played, his confidence at first base and his versatility earned him the title of the best fielder on the U13 team.', 'images/awards/u13_polar.png'],
            [2024, 'U13', 'Cena trenéra &ndash; Jáchym Hanzelín', 'Coach\'s Award &ndash; Jáchym Hanzelín', 'Je jedničkou na catcherovi, kdy na tomto postu odehrál celou sezónu, včetně náročných turnajů. Tento výkon doplnil i slušnou pálkou a tudíž Cena trenérů mu právem náleží.', 'He is the number one catcher, having played the entire season at that position, including demanding tournaments. He also complemented this performance with a decent bat, and therefore the Coaches Award is rightfully his.', 'images/awards/u13_cenaTrenera.png'],
            [2024, 'U13s', 'Nejlepší pálkař &ndash; Nela Janoušová', 'Best Hitter &ndash; Nela Janoušová', 'V letošní sezóně byla nejlepší pálkařkou týmu. Skvěle plnila roli první pálkařky v lineupu, kde se nebála trpělivě čekat a nechat si naházet víc nadhozů. Její jistota na pálce přinášela týmu stabilitu a často pomáhala zahájit úspěšné útočné akce.', 'This season, she was the team\'s best batter. She played her role as the leadoff hitter in the lineup, where she was not afraid to wait patiently and get more pitches thrown at her. Her confidence at the bat brought stability to the team and often helped launch successful offensive actions.', 'images/awards/u13s_palkar.png'],
            [2024, 'U13s', 'Nejlepší polař &ndash; Adéla Badinková', 'Best Fielder &ndash; Adéla Badinková', 'Byla spolehlivou nadhazovačkou číslo 1, která se na hřišti osvědčila i na postech 1. a 3. mety. Na nadhozu se jí podařilo vyřadit 46 pálkařek ze 185 pomocí strikeoutů, což ukazuje její vynikající kontrolu hry a schopnost potrápit soupeře. Je spolehlivou hráčkou týmu, která podává na nadhozu konzistentní a kvalitní výkony.', 'She was a reliable No. 1 pitcher who also proved herself on the field at 1st and 3rd base. She managed to strike out 46 batters out of 185, demonstrating her excellent control of the game and ability to torment opponents. She is a reliable team player who delivers consistent and quality performances on the pitch.', 'images/awards/u13s_polar.png'],
            [2024, 'U13s', 'Cena trenéra &ndash; Alice Škardová', 'Coach\'s Award &ndash; Alice Škardová', 'Zaslouží si ocenění trenérek jako nejužitečnější hráčka za své výkony a všestrannost. Pálkařsky i polařsky se umístila na vynikajícím druhém místě, což svědčí o její stabilní výkonnosti týmu. V obraně nastupovala na post catchera a spojky, zároveň však uměla přejít i na nadhoz. Je díky svě univerzálnosti klíčovou hráčkou týmu.', 'She deserves the coaches\' award as the most valuable player for her performance and versatility. She ranked second in batting and fielding, which is a testament to her consistent performance on the team. She played catcher and shortstop on defense, but she was also able to switch to pitching. She is a key player on the team thanks to her versatility.', 'images/awards/u13s_cenaTrenera.png'],
            [2024, 'U11', 'Nejlepší pálkař &ndash; Filip Posselt', 'Best Hitter &ndash; Filip Posselt', 'Na pálce je velmi trpělivý. Dobře čte nadhozy, má nejvíce met zdarma a nejméně strikeoutů. Jeho pálkařský průměr vystoupal na skvělých .460.', 'He is very patient with the bat. He reads pitches well, has the most free bases and the fewest strikeouts. His batting average has risen to a great .460.', 'images/awards/u11_palkar.png'],
            [2024, 'U11', 'Nejlepší polař &ndash; Šimon Tománek', 'Best Fielder &ndash; Šimon Tománek', 'Na 1. metě je to jistota. Hoďte mu to na jedničku jak chcete, on se třeba roztrhne, ale chytí. \\Cena pro nejlepšího polaře mu s úspěšností v poli .966 zaslouženě náleží.', 'He\'s a sure thing at first base. Throw him a first baseman any way you want, he might get ripped off, but he\'ll catch it. \\The award for best fielder is deservedly his with a .966 fielding percentage.', 'images/awards/u11_polar.png'],
            [2024, 'U11', 'Cena trenéra &ndash; Daniel Šuranyi', 'Coach\'s Award &ndash; Daniel Šuranyi', 'Cenu trenérů si za největší zlepšení během roku a to jak v poli, tak i na pálce, společně s výbornými výkony na nadhazovacím kopci zaslouží práve Dan.', 'Dan deserves the Coaches\' Award for the greatest improvement during the year, both in the field and at bat, along with excellent performances on the mound.', 'images/awards/u11_cenaTrenera.png'],
            [2024, 'U11s', 'Nejlepší pálkař &ndash; Nicol Barešová', 'Best Hitter &ndash; Nicol Barešová', 'Předvedla na pálce vynikající výkony, když ze 75 startů fokázala 48krát úspěšně poslat míč do hry, a to bez jediného strikeoutu. Tato úžasná statistika z ní činí nejlepší pálkařku týmu mladšíxh žákyň U11. Svou precizností a stabilitou na pálce významně přispěla k úspěchu týmu.', 'She showed excellent performances at bat, when out of 75 starts she managed to successfully put the ball in play 48 times, without a single strikeout. This amazing statistic makes her the best batsman of the U11 girls\' team. With her precision and stability at bat, she significantly contributed to the team\'s success.', 'images/awards/u11s_palkar.png'],
            [2024, 'U11s', 'Nejlepší polař &ndash; Julie Rákosníková', 'Best Fielder &ndash; Julie Rákosníková', 'Svými stabilními výkony na pozici spojky a dvojky výrezně přispěla k pevnosti týmové obrany. Její spolehlivost na těchto klíčových postech byla pro tým velmi důležitá a navíc umí zaskočit i v zadním poli, což dokládá její univerzálnost a připravenost podpořit tým, kde je potřeba.', 'With her consistent performances at the shortstop and number two positions, she has contributed significantly to the strength of the team\'s defense. Her reliability at these key positions has been very important for the team, and she can also fill in in the backfield, which demonstrates her versatility and readiness to support the team where needed.', 'images/awards/u11s_polar.png'],
            [2024, 'U11s', 'Cena trenéra &ndash; Ella Maternová', 'Coach\'s Award &ndash; Ella Maternová', 'K týmu se přidala teprve v roce 2023, ale během jedné sezóny udělala obrovský pokrok a rychle se vypracovala na kvalitní hráčku. Svými výkony a přístupem si zajistila místo v základní sestavě, což svědčí o jejím talentu a nasazení. Je skvělým příkladem rychlé adaptace a tvrdé práce týmu.', 'She just joined the team in 2023, but has made huge progress in just one season and has quickly developed into a quality player. Her performances and attitude have earned her a place in the starting lineup, which is a testament to her talent and commitment. She is a great example of the team\'s quick adaptation and hard work.', 'images/awards/u11s_cenaTrenera.png'],
            [2023, 'EXTRA', 'Little League &ndash; Jan Svoboda', 'Little League &ndash; Jan Svoboda', 'Podílel se na úspěchu jako hráč kraje severozápada, který se probojval v evropsko-africké kvalifikaci Little League do finále Little League World Series Intermediate v kalifornském Livermore.', 'He was part of the success as a Northwest Region player who advanced through the Little League Europe-Africa Qualifier to the Little League World Series Intermediate finals in Livermore, California.', ''],
            [2023, 'EXTRA', 'Little League &ndash; Matěj Štilip', 'Little League &ndash; Matěj Štilip', 'Podílel se na úspěchu jako hráč kraje severozápada, který se probojval v evropsko-africké kvalifikaci Little League do finále Little League World Series Intermediate v kalifornském Livermore.', 'He was part of the success as a Northwest Region player who advanced through the Little League Europe-Africa Qualifier to the Little League World Series Intermediate finals in Livermore, California.', ''],
            [2023, 'EXTRA', 'Little League &ndash; Pavel Štilip', 'Little League &ndash; Pavel Štilip', 'Podílel se na úspěchu jako trenér kraje severozápada, který se probojval v evropsko-africké kvalifikaci Little League do finále Little League World Series Intermediate v kalifornském Livermore.', 'He was part of the success as a Northwest Region player who advanced through the Little League Europe-Africa Qualifier to the Little League World Series Intermediate finals in Livermore, California.', ''],
            [2023, 'UMP', 'Rozhodčí roku &ndash; Mikuláš Draxler', 'Umpire of the year &ndash; Mikuláš Draxler', 'Miners se mohou pochlubit tím, že už od 11 let si cíleně vychovává vlastní tým rozhodčích. Ti nejmladší se zaučují v naší zimní KIWI league, ty starší pak během sezóny vidíme na zápasech a turnajích všech mládežnických kategorií. A ty nejstarší a nejzkušenější v juniorských a dospělých soutěžích. Mikuláš Draxler, který reprezentoval Miners na baseballové Evropsko-africké kvalifikaci Little League přebírá tuto cenu.', 'Miners can boast that they have been training their own team of umpires since the age of 11. The youngest ones are trained in our winter KIWI league, the older ones are seen during the season in matches and tournaments of all youth categories. And the oldest and most experienced ones in junior and adult competitions. Mikuláš Draxler, who represented the Miners at the Little League European-African Baseball Qualifier, receives this award.', ''],
            [2023, 'MUŽI', 'MVP &ndash; Filip Kučera', 'MVP &ndash; Filip Kučera', 'Filip se stal klíčovým hráčem pro tým mužů. Bylo úžasné sledovat jak jeho pokrok v různých disciplínách a jeho psychická odolnost se s každým zápasem zvyšovala. Filip byl silnou oporou nejen v defenzívě a při nadhozech, ale také při odpalech.', 'Filip became a key player for the men\'s team. It was amazing to watch his progress in various disciplines and his mental toughness increase with each game. Filip was a strong support not only on defense and pitching, but also batting.', ''],
            [2023, 'ŽENY', 'MVP &ndash; Natálie Tauchenová', 'MVP &ndash; Natálie Tauchenová', 'Natálčin hlavní post je spojka, kde již několik sezón odvádí spolehlivý výkon. V letošní sezóně se velmi zlepšila na nadhozu, což vedlo k významnému zlepšení výsledků zápasů. Svými dlouhými odpaly podpořila tým významně i v útoku.', 'Natalka\'s main position is the shortstop, where she has been performing reliably for several seasons. This season, she has improved a lot in pitching, which has led to a significant improvement in match results. She has also significantly supported the team in attack with her long hits.', ''],
            [2023, 'U16s', 'Nejlepší pálkař &ndash; Veronika Pražanová', 'Best Hitter &ndash; Veronika Pražanová', 'BA 465. Verča patří mezi silové pálkařky týmu, a tak ji sedí i pozice tzv. cleanup hittera. Věříme, že když na ten balon bude víc koukat a nebude ji hlava lítat všude kolem, bude příští rok BA ještě vyšší.', 'BA 465. Verča is one of the team\'s power hitters, so the cleanup hitter position suits her. We believe that if she looks at the ball more and doesn\'t have her head flying all over the place, her BA will be even higher next year.', ''],
            [2023, 'U16s', 'Nejlepší polař &ndash; Ámélie Draxlerová', 'Best Fielder &ndash; Ámélie Draxlerová', 'Áma je dříč, chce to dotáhnout daleko a maká na tom. Po nedávné nemoci se rychle vrátila do tréninkového režimu a znovu podávala báječné výkony. Zdá se, že trénink nepřerušila ani v nemocničním pokoji. Tato cena náleží zaslouženě jí.', 'Áma is a hard worker, she wants to go far and she is working on it. After a recent illness, she quickly returned to the training regime and again performed wonderfully. It seems that she did not stop training even in the hospital room. This award is deservedly hers.', ''],
            [2023, 'U16s', 'Cena trenéra &ndash; Karolína Valentová', 'Coach\'s Award &ndash; Karolína Valentová', 'Kája si tuto cenu vysloužila svojí pílí a snaživostí. Celou sezónu se potýkala se zraněným prstem a i tak měla skoro perfektní docházku. Není to žádná pusinka!', 'Kája earned this award with her diligence and hard work. She struggled with an injured finger the whole season and still had almost perfect attendance. She\'s no pushover!', ''],
            [2023, 'U15', 'Nejlepší pálkař &ndash; Matěj Štilip', 'Best Hitter &ndash; Matěj Štilip', 'Někomu by mohlo přijít jako šok, že Matěj je oceněn v kategorii U15, i když stále věkově patří do U13. Avšak Matěj i tak dal ze všech kluků v U15 nejvíc úspěšných odpalů a toto ocenění mu oprávněně náleží.', 'It might come as a shock to some that Matěj is being awarded in the U15 category, even though he is still in the U13 age group. However, Matěj still hit the most shots of all the boys in the U15 category and this award rightfully belongs to him.', ''],
            [2023, 'U15', 'Nejlepší polař &ndash; Filip Šámal', 'Best Fielder &ndash; Filip Šámal', 'Filip a jeho přesné nadhozy dokázaly zamotat hlavu nejednomu reprezentantovi, kteří končili svůj start na pálce strike outem. Filip vynikal nejen svou hrou na nadhazovacím kopci, ale také byl důležitým pilířem týmu na první metě.', 'Filip and his accurate pitches were able to confuse many a representative, who ended their start at bat with a strike out. Filip not only excelled with his play on the pitching mound, but was also an important pillar of the team at first base.', ''],
            [2023, 'U15', 'Cena trenéra &ndash; Lukáš Mehes', 'Coach\'s Award &ndash; Lukáš Mehes', 'Lukáš za poslední sezónu neuvěřitelně zesílil a zrychlil své atletické dovednosti. V zadním poli dokázal pochytat několik důležitých balónů ze vzduchu. Na pálce patřil do první čtyřky pálkařů.', 'Lukáš has become incredibly stronger and faster in his athleticism over the past season. He has been able to catch several important balls out of the air in the backfield. At bat, he has been a top-four hitter.', ''],
            [2023, 'U13', 'Nejlepší pálkař &ndash; Samuel Horák', 'Best Hitter &ndash; Samuel Horák', 'Samuel Horák je v letošní sezoně bezkonkurenčně nejlepším pálkařem U13. Jeho odpaly znamenaly většinou druhou nebo třetí metu. A v této sezoně si hlavně na své pálkařské konto připsal 5 homerunů!', 'Samuel Horák is the unrivaled best U13 batsman this season. His hits mostly meant second or third base. And this season, he has scored 5 home runs!', ''],
            [2023, 'U13', 'Nejlepší polař &ndash; Matěj Štilip', 'Best Fielder &ndash; Matěj Štilip', 'Jistota na zadákovi, bezchybný i na první metě a v těžkých chvílích dokázal zaskočit i na nadhazovacím kopci. V této sezoně dokázal ukrást největší počet met. Skvělou sezonu korunoval svojí účastí na Světovém finále projektu Little League, které se hrálo v USA.', 'Sure at the back, flawless at first base and in difficult moments he was able to surprise even on the pitcher\'s mound. This season he managed to steal the most bases. He crowned a great season with his participation in the Little League World Finals, which was played in the USA.', ''],
            [2023, 'U13', 'Cena trenéra &ndash; Albertu Chalupovi', 'Coach\'s Award &ndash; Albertu Chalupovi', 'u této ceny měli trenéři rozhodování nejtěžší, protože by si ji zasloužilo víc hráčů. Nicméně v konečném rozhodování připadá toto ocenění Albertu Chalupovi. Nepsaný kapitán týmu zaznamenal největší sportovní růst v této sezóně. Je to dobrý pálkař a opora na třetí metě', 'The coaches had the hardest time deciding on this award, as more players would have deserved it. However, in the end, the award went to Albert Chalupa. The undrafted captain of the team has seen the greatest athletic growth this season. He is a good hitter and a support at third base.', ''],
            [2023, 'U11', 'Nejlepší pálkař &ndash; Adam Jakubov', 'Best Hitter &ndash; Adam Jakubov', 'AVG .313. Nejlepší pálkařský průměr v sezóně.', 'AVG .313. Best batting average of the season.', ''],
            [2023, 'U11', 'Nejlepší polař &ndash; Vašek Svoboda', 'Best Fielder &ndash; Vašek Svoboda', 'FP .657. Cenu dostává za dobrou hru na pozici spojky a za dobrý výkon na nadhazovacím kopci.', 'FP .657. He receives the award for good play at the shortstop position and for good performance on the pitching mound.', ''],
            [2023, 'U11', 'Cena trenéra &ndash; Albert Pavlis', 'Coach\'s Awarda &ndash; Albert Pavlis', 'Cenu dostává za týmový přístup a dobrou práci na tréninku.', 'He receives the award for his team approach and good work in training.', ''],
            [2023, 'U11s', 'Nejlepší pálkař &ndash; Alice Škardová', 'Best Hitter &ndash; Alice Škardová', 'BA 585. 53 startů na pálce v Lize coachballu, z toho 31 hitů, kdy většina končila v zadním poli. Pouze jeden jediný strike out. To je statistika nejlepší pálkařky.', 'BA 585. 53 starts at bat in the Coachball League, 31 hits, most of them in the backfield. Only one strikeout. That\'s the best batter\'s stat.', ''],
            [2023, 'U11s', 'Nejlepší polař &ndash; Kateřina Hergetová', 'Best Fielder &ndash; Kateřina Hergetová', 'A 958. Katku zdobila výborná hra na 1. metě, kdy několikrát podržela tým při velmi těžkých příhozech a zajistila důležité outy. Za celou sezónu v Lize coachballu měla 96 zákroků v poli, z toho pouze 4 chybné.', 'And 958. Katka was decorated with an excellent game at 1st base, where she supported the team several times during very difficult pitches and secured important outs. During the entire season in the Coachball League, she had 96 saves in the field, of which only 4 were errors.', ''],
            [2023, 'U11s', 'Cena trenéra &ndash; Julie Rákosníková', 'Coach\'s Award &ndash; Julie Rákosníková', 'Vytrvalost a píle. Těmito slovy lze popsat Julču. Během sezóny se začala trápit s pálkou, ale nevzdala se a i v důležitých situacích dokázala balón poslat do pole.', 'Perseverance and diligence. These are the words that describe Julča. During the season, she started to struggle with the bat, but she didn\'t give up and even in important situations she was able to send the ball into the field.', ''],
            [2022, 'UMP', 'Rozhodčí roku &ndash; Jan Herget', 'Umpire of the year &ndash; Jan Herget', 'Honza získává cenu za nejvíce odpískaných zápasů a pokrok v průběhu sezóny.', 'Honza wins the award for the most whistled matches and progress during the season.', ''],
            [2022, 'MUŽI', 'MVP &ndash; David Jaklin', 'MVP &ndash; David Jaklin', 'Letošní sezóna se Davidovi velmi vydařila. Ač někteří hráči v jeho věku končí kariéru, David nastupoval pravidelně na postu nadhazovače, kde předváděl velmi stabilní výkon. Na pálce patřil k oporám týmu. Jeho zkušennosti, dobrá hra na pálce i v poli mu zajistily toto ocenění pro sezónu 2022.', 'This season was very successful for David. Although some players his age are ending their careers, David regularly played as a pitcher, where he showed very stable performance. At bat, he was one of the pillars of the team. His experience, good play at bat and in the field secured him this award for the 2022 season.', ''],
            [2022, 'ŽENY', 'MVP &ndash; Máša Pelikánová', 'MVP &ndash; Máša Pelikánová', 'Jejími hlavnímí posty jsou 3. meta a zadák, bez problémů ale dokáže zaskočit i na spojce nebov zadním poli. Působí také jako asistentka trenéra u týmu mladších žákyň.', 'Her main positions are 3rd base and fullback, but she can also fill in at shortstop or in the backfield. She also serves as an assistant coach for the junior varsity team.', ''],
            [2022, 'U16s', 'Cena trenéra &ndash; Natálie Stádníková', 'Coach\'s Award &ndash; Natálie Stádníková', 'Cenu trenéra získává za svědomitost a píli, pracovitost, snaživost a za velký posun na nadhozu.', 'He receives the coach\'s award for his conscientiousness and diligence, hard work, effort, and great progress on the pitch.', ''],
            [2022, 'U15', 'Nejlepší pálkař &ndash; Vojtěch Kuklík', 'Best Hitter &ndash; Vojtěch Kuklík', 'Vojta na sobě tvrdě pracuje každý rok. Vyniká nejen dalekými odpali, ale i rychlostí běhu na metách. Má své stabilní místo v lineupu.', 'Vojta works hard every year. He excels not only with long hits, but also with his speed on the bases. He has a stable place in the lineup.', ''],
            [2022, 'U15', 'Nejlepší polař &ndash; Ondřej Vostatek', 'Best Fielder &ndash; Ondřej Vostatek', 'Ondřej vyniká svojí silnou paží a když nastoupil na pozici nadhazovače, tým hrál velice vyrovnané zápasy s jakýmkoliv soupeřem.', 'Ondřej stands out with his strong arm and when he took the pitcher position, the team played very balanced games with any opponent.', ''],
            [2022, 'U15', 'Cena trenéra &ndash; Jáchym Rak', 'Coach\'s Award &ndash; Jáchym Rak', 'Jáchym je skvělým spoluhráčem. V letošní sezóně si zaslouží cenu trenéra pro jeho 100% účast na trénincích a zápasech. Zaznamenal velký posun na pálce i v poli.', 'Jáchym is a great teammate. This season he deserves the coach\'s award for his 100% participation in training and games. He has made great progress both at bat and in the field.', ''],
            [2022, 'U13', 'Nejlepší pálkař &ndash; Jan Svoboda', 'Best Hitter &ndash; Jan Svoboda', 'Kvalita jeho pálky rostla zápas od zápasu a na konci sezóny ho tak zdobí největší počet odpalů.', 'The quality of his bat grew game by game, and by the end of the season he had the most at-bats.', ''],
            [2022, 'U13', 'Nejlepší polař &ndash; Matěj Štilip', 'Best Fielder &ndash; Matěj Štilip', 'Druhý nejlepší pálkař týmu, nejvíce ukradených met, jistota v zadním poli a excelentní výkony na postu zadáka.', 'The team\'s second best batter, most stolen bases, confidence in the backfield and excellent performances at the fullback position.', ''],
            [2022, 'U13', 'Cena trenéra &ndash; Amélie Draxlerová', 'Coach\'s Award &ndash; Amélie Draxlerová', 'Nejužitečnější hráčka v týmu. Největší počet odehraných zápasů, největší počet doběhnutých bodů, vysoký počet ukradených met, jistota a chladná hlava v duležitých chvílích na nadhozu.', 'The most valuable player on the team. The most games played, the most runs scored, the highest number of stolen bases, confidence and a cool head in important moments on the pitch.', ''],
            [2022, 'U13s', 'Nejlepší pálkař &ndash; Bára Jedelská', 'Best Hitter &ndash; Bára Jedelská', 'BA přes 0,500, v sezóně odpálila i několik homerunů.', 'BA over .500, she also hit several home runs during the season.', ''],
            [2022, 'U13s', 'Nejlepší polař &ndash; Amélie Draxlerová', 'Best Fielder &ndash; Amélie Draxlerová', 'Nejlepší nadhazovačka a hráčka na 1. metě. V sezóně nasázela kolem 100 strike outů.', 'The best pitcher and first baseman. She threw around 100 strikeouts during the season.', ''],
            [2022, 'U13s', 'Cena trenéra &ndash; Štěpánka Stádníková', 'Coach\'s Award &ndash; Štěpánka Stádníková', 'Cenu získává za velký posun na catcherovi a na pálce, za pracovitost, svědomitost a snaživost.', 'She receives the award for his great progress as a catcher and at bat, for his hard work, conscientiousness, and dedication.', ''],
            [2022, 'U11', 'Nejlepší pálkař &ndash; Lukáš Lev', 'Best Hitter &ndash; Lukáš Lev', 'AVG 0,610. Dostává cenu za nejkonzistentnější výkony na pálce v celé sezóně.', 'AVG 0.610. He receives the award for the most consistent performances at bat throughout the season.', ''],
            [2022, 'U11', 'Nejlepší polař &ndash; Vojtěch Mňuk', 'Best Fielder &ndash; Vojtěch Mňuk', 'FA 0,947. Cenu získává za největší zlepšení v poli, konkrétně ve hře na 1. metě.', 'FA 0.947. He wins the award for the greatest improvement in the field, specifically in his play at 1st base.', ''],
            [2022, 'U11', 'Cena trenéra &ndash; Dominik Bernard', 'Coach\'s Award &ndash; Dominik Bernard', 'Cenu trenérá dostává za dobře zvládnutou techniku pálky, za výkony v zadním poli a týmový přístup.', 'The coach\'s award is given for well-mastered batting technique, outfield performance, and team approach.', ''],
        ];
        $stmt = $db->prepare('INSERT INTO awards (year, category, title_cs, title_en, description_cs, description_en, photo, sort_order) VALUES (?,?,?,?,?,?,?,?)');
        foreach ($rows as $i => $r) { $stmt->execute([$r[0], $r[1], $r[2], $r[3], $r[4], $r[5], $r[6], $i]); }
        $inserted['awards'] = count($rows);
    }

    return $inserted;
}
